### ISSUE TITLE
Which ports provided signal increases?

### ISSUE THREAD

**Issue by phr00t** [logich/r910#1]
First, thank you for this information!

You mention "Plugging an antenna into two of the matched pairs does increase the signal (RSSI and RSRQ)", which matched pairs worked for you on the diagram? I was able to drill out the B41 ports to test, which didn't help my signal either.

On this diagram, the B41 ports are the two on the left:

https://raw.githubusercontent.com/logich/r910/master/device-diagram.png

... which other ones worked for you? Was there any material beyond plastic molding destroyed near the port during drilling? Finally, what band did you find improvement on? B41, B25, B26 or all of the above?

**Comment by phr00t** [comment]
According to this image:

https://github.com/logich/r910/blob/master/connected-modem.png

It looks like the ports, using the diagram linked above, show using the bottom left & top right ports.

I didn't notice much RSSI & RSRQ improvement, but I did notice an improvement in Signal to Noise ratio & most importantly -- upload & download speeds on Band 25.

**Comment by logich** [comment]
I have some additional pics I need to post, but my improvements were on stability and speed of link with really minor changes in RSSI. 

Regards,

-Logan

On Aug 27, 2018, at 6:18 PM, Phr00t <notifications@github.com> wrote:

According to this image:

https://github.com/logich/r910/blob/master/connected-modem.png

It looks like the ports, using the diagram linked above, show using the bottom left & top right ports.

I didn't notice much RSSI & RSRQ improvement, but I did notice an improvement in Signal to Noise ratio & most importantly -- upload & download speeds on Band 25.
